тест к функции compare - сравнить 3 пары чисел.
Но функция compare имеет сигнатуру void compare(int a, int b), т.е. теоретически при дальнейшем развитии программы и изменении функции есть вероятность, что 
a и b могут быть изменены внутри функции при каких-то условиях. И тогда 3 пары чисел, возможно, будет недостаточно. Т.е. три пары числе могут как пройти тест, так и провалить, в зависимости от значений a и b.
Например, вдруг внутри функции compare в результате ошибки в коде при a>100 выполняется присвоение a=0. 
Тогда пара a=50 и b=10 даст правильный результат при тестировании, и функцию посчитаем правильно работающей. А потом в реальной работе будет a=150 и b=10 - результат будет неверный и никто об этом не узнает.

тесты в Catch2 могут проверять только результаты сравнения? А если результат заренее неизвестен? 
А если функция предназначена, например, для передачи данных внешнему устройству? ее можно проверить  с помощью catch?
Или наоборот - функция нужна для получения данных из параллельного потока. Как проверить, что работа функции не пропускает данные в результате подвисания или блокировки? 